Repository codurance/katalyst-by-codurance-microsite, pull requests merged in 2023-07, with the labels that each got.

#3 Initial-base-components
  version_control/katalyst_by_codurance/css/components/_footer.css
  version_control/katalyst_by_codurance/css/components/_header.css
  version_control/katalyst_by_codurance/css/elements/_colors.css
  version_control/katalyst_by_codurance/css/elements/_typography.css
  version_control/katalyst_by_codurance/css/generic/_reset.css
  version_control/katalyst_by_codurance/css/main.css
  version_control/katalyst_by_codurance/css/modules/language-selector.css
  version_control/katalyst_by_codurance/css/objects/_containers-dnd.css
  version_control/katalyst_by_codurance/css/objects/_layout.css
  version_control/katalyst_by_codurance/css/theme-overrides.css
  version_control/katalyst_by_codurance/css/tools/_breakpoints.css
  version_control/katalyst_by_codurance/images/spacing-px-values.png
  version_control/katalyst_by_codurance/images/template-previews/home.png
  version_control/katalyst_by_codurance/images/typography-px-values.png
  version_control/katalyst_by_codurance/modules/Language-Selector.module/fields.json
  version_control/katalyst_by_codurance/modules/Language-Selector.module/meta.json
  version_control/katalyst_by_codurance/modules/Language-Selector.module/module.html
  version_control/katalyst_by_codurance/templates/home.html
  version_control/katalyst_by_codurance/templates/layouts/base.html
  version_control/katalyst_by_codurance/templates/partials/footer.html
  version_control/katalyst_by_codurance/templates/partials/header.html
  version_control/katalyst_by_codurance/templates/qa-test.html
  version_control/katalyst_by_codurance/templates/system/membership-login.html
  version_control/katalyst_by_codurance/templates/system/membership-register.html
  version_control/katalyst_by_codurance/templates/system/membership-reset-password-request.html
  version_control/katalyst_by_codurance/templates/system/membership-reset-password.html
  version_control/katalyst_by_codurance/templates/system/password-prompt.html
  version_control/katalyst_by_codurance/templates/system/search-results.html
Labels: documentation, enhancement

#5 New-section/features-listing
  version_control/katalyst_by_codurance/css/generic/_reset.css
  version_control/katalyst_by_codurance/css/modules/benefits-listing.css
  version_control/katalyst_by_codurance/css/objects/_layout.css
  version_control/katalyst_by_codurance/css/templates/home.css
  version_control/katalyst_by_codurance/css/tools/_breakpoints.css
  version_control/katalyst_by_codurance/modules/Benefits-Listing.module/fields.json
  version_control/katalyst_by_codurance/modules/Benefits-Listing.module/meta.json
  version_control/katalyst_by_codurance/modules/Benefits-Listing.module/module.html
  version_control/katalyst_by_codurance/templates/home.html
Labels: documentation, enhancement

#6 New-section/clients-logo-module
  version_control/katalyst_by_codurance/css/modules/logos-cloud.css
  version_control/katalyst_by_codurance/css/objects/_layout.css
  version_control/katalyst_by_codurance/css/templates/home.css
  version_control/katalyst_by_codurance/modules/Logos-Cloud.module/fields.json
  version_control/katalyst_by_codurance/modules/Logos-Cloud.module/meta.json
  version_control/katalyst_by_codurance/modules/Logos-Cloud.module/module.html
  version_control/katalyst_by_codurance/templates/home.html
Labels: enhancement

#7 New-section/methodology
  version_control/katalyst_by_codurance/css/templates/home.css
  version_control/katalyst_by_codurance/templates/home.html
Labels: enhancement

#8 New-section/testimonials
  version_control/katalyst_by_codurance/css/elements/_typography.css
  version_control/katalyst_by_codurance/css/modules/testimonial.css
  version_control/katalyst_by_codurance/css/templates/home.css
  version_control/katalyst_by_codurance/css/theme-overrides.css
  version_control/katalyst_by_codurance/modules/Testimonial.module/fields.json
  version_control/katalyst_by_codurance/modules/Testimonial.module/meta.json
  version_control/katalyst_by_codurance/modules/Testimonial.module/module.html
  version_control/katalyst_by_codurance/templates/home.html
Labels: enhancement

#9 New-section/contact-form
  version_control/katalyst_by_codurance/css/components/_default-modules.css
  version_control/katalyst_by_codurance/css/elements/_buttons.css
  version_control/katalyst_by_codurance/css/elements/_colors.css
  version_control/katalyst_by_codurance/css/elements/_forms.css
  version_control/katalyst_by_codurance/css/templates/home.css
  version_control/katalyst_by_codurance/css/theme-overrides.css
  version_control/katalyst_by_codurance/fields.json
  version_control/katalyst_by_codurance/templates/home.html
Labels: enhancement

#10 Fix/minor-style-adjustments
  version_control/katalyst_by_codurance/css/templates/home.css
Labels: bug

#11 New-section/services
  version_control/katalyst_by_codurance/css/elements/_typography.css
  version_control/katalyst_by_codurance/css/modules/services-cards.css
  version_control/katalyst_by_codurance/css/templates/home.css
  version_control/katalyst_by_codurance/modules/Services-Cards.module/fields.json
  version_control/katalyst_by_codurance/modules/Services-Cards.module/meta.json
  version_control/katalyst_by_codurance/modules/Services-Cards.module/module.html
  version_control/katalyst_by_codurance/templates/home.html
Labels: enhancement

#12 Update/design-adjustments
  version_control/katalyst_by_codurance/css/components/_header.css
  version_control/katalyst_by_codurance/css/elements/_buttons.css
  version_control/katalyst_by_codurance/css/elements/_typography.css
  version_control/katalyst_by_codurance/css/modules/language-selector.css
  version_control/katalyst_by_codurance/css/templates/home.css
  version_control/katalyst_by_codurance/templates/home.html
  version_control/katalyst_by_codurance/templates/layouts/base.html
  version_control/katalyst_by_codurance/templates/partials/header.html
Labels: bug, enhancement

#13 Redesign/client-logos
  version_control/katalyst_by_codurance/css/modules/logos-cloud.css
  version_control/katalyst_by_codurance/css/templates/home.css
Labels: enhancement
