Repository codurance/katalyst-by-codurance-microsite, pull requests merged in 2023-12, with the labels that each got.

#35 Create/couse-page-template
  version_control/katalyst_by_codurance/css/modules/accordion.css
  version_control/katalyst_by_codurance/css/modules/icon-text-listing.css
  version_control/katalyst_by_codurance/css/objects/_layout.css
  version_control/katalyst_by_codurance/css/templates/course-page.css
  version_control/katalyst_by_codurance/images/template-previews/course-page-preview.png
  version_control/katalyst_by_codurance/modules/Accordion.module/fields.json
  version_control/katalyst_by_codurance/modules/Accordion.module/meta.json
  version_control/katalyst_by_codurance/modules/Accordion.module/module.html
  version_control/katalyst_by_codurance/modules/Icon-Text-Listing.module/fields.json
  version_control/katalyst_by_codurance/modules/Icon-Text-Listing.module/meta.json
  version_control/katalyst_by_codurance/modules/Icon-Text-Listing.module/module.html
  version_control/katalyst_by_codurance/templates/course-page.html
Labels: enhancement

#36 Update/course-page-template/aside-responsive-adjustments
  version_control/katalyst_by_codurance/css/templates/course-page.css
  version_control/katalyst_by_codurance/templates/course-page.html
  version_control/katalyst_by_codurance/templates/layouts/base.html
Labels: bug, enhancement

#37 Update/template/course-pages/format-adjustments
  version_control/katalyst_by_codurance/templates/course-page.html
Labels: bug, enhancement

#38 Amend module paths and labels
  version_control/katalyst_by_codurance/templates/course-page.html
Labels: bug

#39 Update/template/course-page/course-info-mobile
  version_control/katalyst_by_codurance/css/templates/course-page.css
  version_control/katalyst_by_codurance/templates/course-page.html
Labels: enhancement

#40 Update/course-page/course-info/change-video-for-image
  version_control/katalyst_by_codurance/css/elements/_typography.css
  version_control/katalyst_by_codurance/css/templates/course-page.css
  version_control/katalyst_by_codurance/templates/course-page.html
Labels: enhancement
